Traceback (most recent call last):
  File "/home/haoting/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/haoting/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/haoting/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/haoting/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/haoting/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/home/haoting/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/haoting/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig = plt.figure(constrained_layout=True, figsize=(7, 11), height_ratios=[1, 2])
subfigs = fig.subfigures(2, 1)
axsTopRight = subfigs[0].subplots(1, 2, sharey=False)
sns.barplot(data=network_mod['data'],
            orient='h',
            ci=None,
            order=network_mod['order'],
            color=bar_color, ax=axsTopRight[0])
axsTopRight[0].set_title(network_mod['title'])
axsTopRight[0].set(xlabel=network_mod['label'])
axsTopRight[0].set(ylabel="Confound removal strategy")

sns.barplot(data=corr_mod['data'], x='correlation', y='strategy',
            ci=None,
            order=None,
            color=bar_color, ax=axsTopRight[1])
axsTopRight[1].set_title(corr_mod['title'])
axsTopRight[1].set(xlabel=corr_mod['label'])

fig.suptitle('Correlation between\nnetwork modularity and mean framewise displacement')

axsBottomRight = subfigs[1].subplots(3, 4, sharex=True, sharey=True)
for i, row_axes in enumerate(axsBottomRight):
    for j, ax in enumerate(row_axes):
        if cur_strategy := grid_location.get((i, j), False):
            mask = long_qcfc["Strategy"] == cur_strategy
            g = sns.histplot(data=long_qcfc.loc[mask, :],
                            x='qcfc',
                            ax=ax)
            g.set_title(cur_strategy, fontsize='small')
            mad = qcfc_mad['data'][cur_strategy].values
            g.axvline(mad, linewidth=1, linestyle='--', color='r')
            xlabel = "Pearson\'s correlation" if i == 2 else None
            g.set(xlabel=xlabel)
        else:
            subfigs[1].delaxes(axsBottomRight[i, j])
subfigs[1].suptitle('Distribution of correlation between framewise distplacement and edge strength')


glue("network-fig", fig, display=False)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_28610/3514595957.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mfig[0m [0;34m=[0m [0mplt[0m[0;34m.[0m[0mfigure[0m[0;34m([0m[0mconstrained_layout[0m[0;34m=[0m[0;32mTrue[0m[0;34m,[0m [0mfigsize[0m[0;34m=[0m[0;34m([0m[0;36m7[0m[0;34m,[0m [0;36m11[0m[0;34m)[0m[0;34m,[0m [0mheight_ratios[0m[0;34m=[0m[0;34m[[0m[0;36m1[0m[0;34m,[0m [0;36m2[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0msubfigs[0m [0;34m=[0m [0mfig[0m[0;34m.[0m[0msubfigures[0m[0;34m([0m[0;36m2[0m[0;34m,[0m [0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0maxsTopRight[0m [0;34m=[0m [0msubfigs[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m.[0m[0msubplots[0m[0;34m([0m[0;36m1[0m[0;34m,[0m [0;36m2[0m[0;34m,[0m [0msharey[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m sns.barplot(data=network_mod['data'],
[1;32m      5[0m             [0morient[0m[0;34m=[0m[0;34m'h'[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/matplotlib/pyplot.py[0m in [0;36mfigure[0;34m(num, figsize, dpi, facecolor, edgecolor, frameon, FigureClass, clear, **kwargs)[0m
[1;32m    795[0m                 RuntimeWarning)
[1;32m    796[0m [0;34m[0m[0m
[0;32m--> 797[0;31m         manager = new_figure_manager(
[0m[1;32m    798[0m             [0mnum[0m[0;34m,[0m [0mfigsize[0m[0;34m=[0m[0mfigsize[0m[0;34m,[0m [0mdpi[0m[0;34m=[0m[0mdpi[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    799[0m             [0mfacecolor[0m[0;34m=[0m[0mfacecolor[0m[0;34m,[0m [0medgecolor[0m[0;34m=[0m[0medgecolor[0m[0;34m,[0m [0mframeon[0m[0;34m=[0m[0mframeon[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/matplotlib/pyplot.py[0m in [0;36mnew_figure_manager[0;34m(*args, **kwargs)[0m
[1;32m    314[0m     [0;34m"""Create a new figure manager instance."""[0m[0;34m[0m[0;34m[0m[0m
[1;32m    315[0m     [0m_warn_if_gui_out_of_main_thread[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 316[0;31m     [0;32mreturn[0m [0m_backend_mod[0m[0;34m.[0m[0mnew_figure_manager[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    317[0m [0;34m[0m[0m
[1;32m    318[0m [0;34m[0m[0m

[0;32m~/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/matplotlib/backend_bases.py[0m in [0;36mnew_figure_manager[0;34m(cls, num, *args, **kwargs)[0m
[1;32m   3542[0m         [0;32mfrom[0m [0mmatplotlib[0m[0;34m.[0m[0mfigure[0m [0;32mimport[0m [0mFigure[0m[0;34m[0m[0;34m[0m[0m
[1;32m   3543[0m         [0mfig_cls[0m [0;34m=[0m [0mkwargs[0m[0;34m.[0m[0mpop[0m[0;34m([0m[0;34m'FigureClass'[0m[0;34m,[0m [0mFigure[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 3544[0;31m         [0mfig[0m [0;34m=[0m [0mfig_cls[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   3545[0m         [0;32mreturn[0m [0mcls[0m[0;34m.[0m[0mnew_figure_manager_given_figure[0m[0;34m([0m[0mnum[0m[0;34m,[0m [0mfig[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   3546[0m [0;34m[0m[0m

[0;31mTypeError[0m: __init__() got an unexpected keyword argument 'height_ratios'
TypeError: __init__() got an unexpected keyword argument 'height_ratios'

