Traceback (most recent call last):
  File "/home/haoting/.virtualenvs/fmriprep-denoise-benchmark/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/haoting/.virtualenvs/fmriprep-denoise-benchmark/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/haoting/.virtualenvs/fmriprep-denoise-benchmark/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/haoting/.virtualenvs/fmriprep-denoise-benchmark/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/haoting/.virtualenvs/fmriprep-denoise-benchmark/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/haoting/.virtualenvs/fmriprep-denoise-benchmark/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/haoting/.virtualenvs/fmriprep-denoise-benchmark/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import warnings

warnings.filterwarnings('ignore')
from fmriprep_denoise.visualization import figures
from myst_nb import glue

# Load metric data
dataset = 'ds000030'
atlases = ['mist', 'difumo', 'schaefer7networks', 'gordon333']
groups = ['full_sample', 'CONTROL', 'SCHZ', 'BIPOLAR', 'ADHD']
for atlas in atlases:
    for group in groups:
        fig = figures.plot_motion_resid(dataset, path_root, atlas, group=group)
        glue(f'{dataset}_{group}_{atlas}_qcfc-fig', fig, display=False)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 11>[0;34m()[0m
[1;32m     11[0m [38;5;28;01mfor[39;00m atlas [38;5;129;01min[39;00m atlases:
[1;32m     12[0m     [38;5;28;01mfor[39;00m group [38;5;129;01min[39;00m groups:
[0;32m---> 13[0m         fig [38;5;241m=[39m figures[38;5;241m.[39mplot_motion_resid(dataset, [43mpath_root[49m, atlas, group[38;5;241m=[39mgroup)
[1;32m     14[0m         glue([38;5;124mf[39m[38;5;124m'[39m[38;5;132;01m{[39;00mdataset[38;5;132;01m}[39;00m[38;5;124m_[39m[38;5;132;01m{[39;00mgroup[38;5;132;01m}[39;00m[38;5;124m_[39m[38;5;132;01m{[39;00matlas[38;5;132;01m}[39;00m[38;5;124m_qcfc-fig[39m[38;5;124m'[39m, fig, display[38;5;241m=[39m[38;5;28;01mFalse[39;00m)

[0;31mNameError[0m: name 'path_root' is not defined
NameError: name 'path_root' is not defined

