Traceback (most recent call last):
  File "/home/haoting/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/haoting/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/haoting/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/haoting/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/haoting/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/home/haoting/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/haoting/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, groups = figures.plot_dof_dataset()
glue(f'dof-fig', fig, display=False)
for group in groups:
    d, g = group
    glue(f'group-order_{d}', g, display=False)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m/tmp/ipykernel_60252/1429411138.py[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0mglue[0m[0;34m([0m[0;34mf'dof-fig'[0m[0;34m,[0m [0mfig[0m[0;34m,[0m [0mdisplay[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;32mfor[0m [0mgroup[0m [0;32min[0m [0mgroups[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m     [0md[0m[0;34m,[0m [0mg[0m [0;34m=[0m [0mgroup[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m     [0mglue[0m[0;34m([0m[0;34mf'group-order_{d}'[0m[0;34m,[0m [0mg[0m[0;34m,[0m [0mdisplay[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mValueError[0m: too many values to unpack (expected 2)
ValueError: too many values to unpack (expected 2)

